variable "region" { default = "us-east-1" }
variable "vpc_cidr_block" { default = "10.0.0.0/16" }      #vpc
variable "public_cidr_block1" { default = "10.0.1.0/24" }  # public  subnet 1
variable "public_cidr_block2" { default = "10.0.2.0/24" }  # public  subnet 2
variable "public_cidr_block3" { default = "10.0.3.0/24" }  # public  subnet 3
variable "private_cidr_block1" { default = "10.0.4.0/24" } # private subnet 1
variable "private_cidr_block2" { default = "10.0.5.0/24" } # private subnet 2
variable "private_cidr_block3" { default = "10.0.6.0/24" } # private subnet 3
variable "allocated_storage" { default = 20 }
variable "engine" { default = "mysql" }
variable "identifier" { default = "mydb" }
variable "storage_type" { default = "gp2" }
variable "engine_version" { default = "5.7" }
variable "instance_class" { default = "db.t3.micro" }
variable "name" { default = "mydb" }
variable "username" { default = "foo" }
variable "password" { default = "foobarbaz" }
variable "parameter_group_name" { default = "default.mysql5.7" }
variable "port" { default = 3306 }
